dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install codecov
script:
  - pytest
  - coverage run -m unittest discover
after_success:
  - codecov
branches:
  only:
    - master
